[project]
name = "model"
version = "0.1.0"
description = "ספריית חיזוי פשוטה"
license = {text = "MIT"}

dependencies = [
    "pandas",
    "scikit-learn"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
